# This workflow will test only https://github.com/google/neural-tangents/pull/142
# Copied from github.com/google/jax-md and github.com/google/jax
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: sketching

on:
  push:
    branches:
    - '*/NT'

  pull_request:
    branches:
    - main

jobs:
  Sketching:

    timeout-minutes: 240

    strategy:
      matrix:
        python-version: [3.7]
        JAX_ENABLE_X64: [0, 1]

    runs-on: ubuntu-latest

    steps:

    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2.4.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy jaxlib --upgrade
        pip install  -e .
        pip install -e .[testing]
        pip install pytest
        pip install pytest-xdist
        pip install pytest-cov

    - name: Test with pytest and generate coverage report (Ubuntu)
      run: |
        JAX_ENABLE_X64=${{ matrix.JAX_ENABLE_X64 }} PYTHONHASHSEED=0 pytest experimental/tests/ -n auto --cov=experimental/ --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.xml

    # The below step just reports the success or failure of tests as a "commit status".
    # This is needed for copybara integration.
    - name: Report success or failure as github status
      if: always()
      shell: bash
      run: |
        status="${{ job.status }}"
        lowercase_status=$(echo $status | tr '[:upper:]' '[:lower:]')
        curl -sS --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
           "state": "'$lowercase_status'",
           "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
           "description": "'$status'",
           "context": "github-actions/sketching"
           }'
